// Generated by CoffeeScript 1.3.2
(function() {
  var file, fs, last_state, state;

  fs = require('fs');

  file = '/tmp/decibel.txt';

  fs = require('fs');

  state = 'land';

  last_state = null;

  setInterval(function() {
    return fs.readFile(file, 'utf8', function(err, data) {
      var tier;
      tier = parseInt(data);
      if (parseInt(data) < -5) {
        state = 'land';
      } else {
        state = 'up';
      }
      if (state !== last_state) {
        console.log(state);
      }
      return last_state = state;
    });
  }, 30);

}).call(this);
